# Generated by Django 5.0.3 on 2024-04-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='caracteristica',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='raca',
            name='nivel_cuidado',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Médio'), ('Pequeno', 'Pequeno'), ('Diversificado', 'Diversificado'), ('N/A', 'N/A')], default='DIVERSIFICADO', max_length=20),
        ),
    ]
