# Generated by Django 5.0.3 on 2024-04-04 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0002_alter_raca_caracteristica_alter_raca_nivel_cuidado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='caracteristica',
            field=models.TextField(max_length=5000),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('historico', models.TextField(max_length=5000)),
                ('raca_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CadastroPet.raca')),
            ],
        ),
    ]
