# Generated by Django 5.0.3 on 2024-04-04 22:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0003_alter_raca_caracteristica_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='historico',
            field=models.TextField(default='N/A', max_length=5000),
        ),
        migrations.AlterField(
            model_name='raca',
            name='caracteristica',
            field=models.TextField(default='N/A', max_length=5000),
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('vacinacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_vacinacao', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(help_text='<Detalhe aqui a vacinação...>', max_length=5000)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CadastroPet.pet')),
            ],
        ),
    ]
