# Generated by Django 5.0.3 on 2024-04-04 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0004_alter_pet_historico_alter_raca_caracteristica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vacinacao',
            name='data_vacinacao',
            field=models.DateField(default=django.utils.timezone.now, help_text='Use o formato: <em>DD-MM-YYYY</em>.'),
        ),
        migrations.AlterField(
            model_name='vacinacao',
            name='descricao',
            field=models.TextField(help_text='Detalhe aqui a vacinação', max_length=5000),
        ),
    ]
