# Generated by Django 5.0.3 on 2024-05-01 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0005_pet_foto_alter_vacinacao_data_vacinacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('C', 'Canina'), ('F', 'Felina')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pet/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='historico',
            field=models.TextField(default='N/A', help_text='Digite os antecedentes do animal e características de personalidade e comportamentais.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadastroPet.raca'),
        ),
        migrations.AlterField(
            model_name='raca',
            name='nivel_cuidado',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Médio'), ('Baixo', 'Baixo'), ('Diversificado', 'Diversificado'), ('N/A', 'N/A')], default='DIVERSIFICADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacinacao',
            name='pet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadastroPet.pet'),
        ),
    ]
