# Generated by Django 5.0.3 on 2024-05-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0006_pet_especie_alter_pet_foto_alter_pet_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='divulga',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', help_text='Permite texto de divulgação externa?', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='texto_divulga',
            field=models.TextField(default='N/A', help_text='Digite o texto para divulgação externa.', max_length=5000),
        ),
    ]
