# Generated by Django 5.0.3 on 2024-05-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0009_pet_temperamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='doencas',
            field=models.TextField(default='N/A', help_text='Digite as doenças do animal.', max_length=5000),
        ),
    ]
