# Generated by Django 5.0.3 on 2024-05-01 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0010_pet_doencas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='data_obito',
            field=models.DateField(null=True, verbose_name='Data do óbito'),
        ),
        migrations.AddField(
            model_name='pet',
            name='motivo_obito',
            field=models.CharField(max_length=100, null=True, verbose_name='Motivo óbito'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='data_chegada',
            field=models.DateField(verbose_name='Data de Chegada na ONG'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data do nascimento'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='divulga',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], help_text='Permite texto de divulgação externa?', max_length=1, verbose_name='Divulgação'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('C', 'Canina'), ('F', 'Felina')], max_length=1, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pet/', verbose_name='Foto do crachá'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='historico',
            field=models.TextField(default='N/A', help_text='Digite os antecedentes do animal e características de personalidade e comportamentais.', max_length=5000, verbose_name='Histórico'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nome_ninhada',
            field=models.CharField(default='N/A', help_text='Digite o nome da ninhada a que pertente.', max_length=100, verbose_name='Nome da ninhada'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1, verbose_name='Porte do animal'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadastroPet.raca', verbose_name='ID da raça'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='temperamento',
            field=models.CharField(choices=[('N', 'Normal'), ('H', 'Hiperativo'), ('M', 'Medroso'), ('A', 'Agressivo'), ('S', 'Manso'), ('C', 'Sociável com outros animais'), ('O', 'Outros')], max_length=1, verbose_name='Temperamento do animal'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='texto_divulga',
            field=models.TextField(default='N/A', help_text='Digite o texto para divulgação externa.', max_length=5000, verbose_name='Texto para divulgação'),
        ),
    ]
