# Generated by Django 5.0.3 on 2024-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0011_pet_data_obito_pet_motivo_obito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='data_obito',
            field=models.DateField(blank=True, null=True, verbose_name='Data do óbito'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='doencas',
            field=models.TextField(blank=True, default='N/A', help_text='Digite as doenças do animal.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_pet/', verbose_name='Foto do crachá'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='historico',
            field=models.TextField(blank=True, default='N/A', help_text='Digite os antecedentes do animal e características de personalidade e comportamentais.', max_length=5000, null=True, verbose_name='Histórico'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='motivo_obito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo óbito'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nome_ninhada',
            field=models.CharField(blank=True, default='N/A', help_text='Digite o nome da ninhada a que pertente.', max_length=100, null=True, verbose_name='Nome da ninhada'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='texto_divulga',
            field=models.TextField(blank=True, default='N/A', help_text='Digite o texto para divulgação externa.', max_length=5000, null=True, verbose_name='Texto para divulgação'),
        ),
    ]
