# Generated by Django 5.0.3 on 2024-05-11 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0013_funcionario_usuario_funcionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('voluntario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_voluntario', models.CharField(max_length=100, verbose_name='Nome do Voluntario')),
                ('endereço_voluntario', models.CharField(max_length=200, verbose_name='Endereço do Voluntario')),
                ('atribuicao_voluntario', models.TextField(help_text='Detalhe aqui as atribuições do voluntário', max_length=5000, verbose_name='Atribuições do Voluntario')),
                ('email_voluntario', models.CharField(max_length=50, verbose_name='E-mail do Voluntario')),
                ('telefone_voluntario', models.CharField(max_length=30, verbose_name='Telefone do Voluntario')),
                ('usuario_voluntario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
