# Generated by Django 5.0.3 on 2024-05-11 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0014_voluntario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='usuario_funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='usuario_voluntario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('patrocinador_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_patrocinador', models.CharField(max_length=100, verbose_name='Nome do Patrocinador')),
                ('endereço_patrocinador', models.CharField(max_length=200, verbose_name='Endereço do Patrocinador')),
                ('email_patrocinador', models.CharField(max_length=50, verbose_name='E-mail do Patrocinador')),
                ('telefone_patrocinador', models.CharField(max_length=30, verbose_name='Telefone do Patrocinador')),
                ('descricao_patrocinio', models.TextField(help_text='Detalhe aqui o patrocínio', max_length=5000, verbose_name='Descrição do Patrocínio')),
                ('usuario_patrocinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Sistema do Patrocinador')),
            ],
        ),
    ]
