# Generated by Django 5.0.3 on 2024-05-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0015_alter_funcionario_usuario_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='tipo_patrocinio',
            field=models.CharField(choices=[('1', 'Financeiro'), ('2', 'Serviços Veterinários'), ('3', 'Alimentos e Suprimentos'), ('4', 'Esterilização/Castração'), ('0', 'Outros')], default='0', max_length=1, verbose_name='Tipo de Patrocínio'),
            preserve_default=False,
        ),
    ]
