# Generated by Django 5.0.3 on 2024-05-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0016_patrocinador_tipo_patrocinio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinador',
            name='descricao_patrocinio',
            field=models.TextField(blank=True, help_text='Detalhe aqui o patrocínio', max_length=5000, null=True, verbose_name='Descrição do Patrocínio'),
        ),
    ]
