# Generated by Django 5.0.3 on 2024-05-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0017_alter_patrocinador_descricao_patrocinio'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='pets_patrocinados',
            field=models.ManyToManyField(to='CadastroPet.pet'),
        ),
    ]
