# Generated by Django 5.0.3 on 2024-05-12 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0018_patrocinador_pets_patrocinados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('adotante_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_adotante', models.CharField(max_length=100, verbose_name='Nome do Adontante')),
                ('endereço_adotante', models.CharField(max_length=200, verbose_name='Endereço do Adontante')),
                ('email_adotante', models.CharField(max_length=50, verbose_name='E-mail do Adontante')),
                ('telefone_adotante', models.CharField(max_length=30, verbose_name='Telefone do Adontante')),
                ('observacao_adotante', models.TextField(blank=True, help_text='Detalhe aqui a obsrevação da Adoção/Adontante', max_length=5000, null=True, verbose_name='Observação da Adoção/Adotante')),
                ('pets_adotados', models.ManyToManyField(limit_choices_to={'status_adocao': 'D'}, to='CadastroPet.pet')),
                ('usuario_adotante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Sistema do Adontante')),
            ],
        ),
    ]
