# Generated by Django 5.0.3 on 2024-05-12 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroPet', '0019_adotante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LarTemporario',
            fields=[
                ('lartemporario_id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_lartemporario', models.CharField(max_length=100, verbose_name='Nome do Lar Temporário')),
                ('responsavel_lartemporario', models.CharField(max_length=100, verbose_name='Nome do responsável pelo Lar Temporário')),
                ('endereço_lartemporario', models.CharField(max_length=200, verbose_name='Endereço do Lar Temporário')),
                ('email_lartemporario', models.CharField(max_length=50, verbose_name='E-mail do Lar Temporário')),
                ('telefone_lartemporario', models.CharField(max_length=30, verbose_name='Telefone do Lar Temporário')),
                ('observacao_lartemporario', models.TextField(blank=True, help_text='Detalhe aqui a observação do Lar Temporário', max_length=5000, null=True, verbose_name='Observação do Lar Temporário')),
                ('capacidade_laartemporario', models.IntegerField(verbose_name='Capacidade do Lar Temporário')),
                ('pets_lartemporario', models.ManyToManyField(help_text='Selecione os PETs para este Lar Temporário', limit_choices_to={'status_adocao__ne': 'A'}, to='CadastroPet.pet', verbose_name='Selecione os PETs para este Lar Temporário')),
                ('usuario_alartemporario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Sistema do Lar Temporário')),
            ],
        ),
    ]
